export type DriftType =
  | "NO_DRIFT"
  | "TRANSIENT_FAILURE"
  | "EXTRACTION_DRIFT"
  | "SEMANTIC_DRIFT"
  | "AMBIGUOUS_DRIFT";

export type ReasonCode =
  | "BASELINE_ESTABLISHED"
  | "SEMANTIC_HASH_UNCHANGED"
  | "SEMANTIC_FIELD_CHANGED"
  | "REQUIRED_FIELD_MISSING"
  | "UNSAFE_VALUE"
  | "COLLECTION_FAILED"
  | "EXTRACTION_VALIDATION_FAILED";

export type HealthState =
  | "HEALTHY"
  | "SUSPECT"
  | "QUARANTINED"
  | "HEALING"
  | "AWAITING_APPROVAL"
  | "VERIFIED"
  | "FAILED";
